data_dir: timm/data
dataset: torch/cifar10
data_dir_id: /path/to/data
dataset_id: soft/cifar10
ood_transforms_eval: "gaussian_noise shot_noise impulse_noise defocus_blur"
severity: 2
is_evaluate_gt: true
method: deterministic
loss: cross-entropy
model: wide_resnet26_10_cifar_preact
pretrained: false
num_classes: 10
img_size: 32
crop_pct: 1
mean: "0.4914 0.4822 0.4465"
std: "0.2023 0.1994 0.2010"
no_prefetcher: true
opt: momentum
momentum: 0.9
weight_decay: 0.0001
sched: cosine
lr: 0.1
smoothing: 0
experiment: deterministic
epochs: 200
log_interval: 3
amp_dtype: bfloat16
workers: 1
batch_size: 128
padding: 2
is_evaluate_on_test_sets: true